### ISSUE TITLE
Language selector and translated routes

### ISSUE THREAD

**Issue by soluxima-erik** [mcamara/laravel-localization#117]
P.S. Best localizer for laravel!!! Thanks for your work.

I am using your code for language selector

``` php
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <li>
            <a rel="alternate" hreflang="{{$localeCode}}" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">
                {{{ $properties['native'] }}}
            </a>
        </li>
    @endforeach
```

however, it does not output the translated routes. How would I go about doing that?
Currently, when Finnish is active, the html output from the above code is:

``` html
<li><a rel="alternate" href="http://domain/en/raportti/1">English</li>
<li><a rel="alternate" href="http://domain/fi/raportti/1">Suomi</li>
```

It should be:

``` html
<li><a rel="alternate" href="http://domain/en/report/1">English</li>
<li><a rel="alternate" href="http://domain/fi/raportti/1">Suomi</li>
```

Everything works correctly with the translated routes as per your instructions and if I go to the pages manually they resolve to the same controller. I just need the language bar output to translate the respective urls to their translated routes.

**Comment by mjmlvp** [comment]
Though this issue is closed I wonder if I can still mention something?
The reason for this error is nowhere mentioned. the reason is that the trans( ) laravel helper function in Laravel 5.2 and 5.3 has the definition

> public function trans($id, array $parameters = [], $domain = 'messages', $locale = null)
(which is not compatible with the calls from LaravelLocalization)

whereas starting from Laravel 5.4 the definition has become

> public function trans($key, array $replace = [], $locale = null)
(which IS compatible with the calls from LaravelLocalization)

For me a solution was to upgrade to laravel 5.4
so the README.md line,
> 5.2.x-5.4.x (PHP 7 not required) | 1.2.x
does not tell the whole story.
Laravel 5.2 and 5.3 work with  Laravellocalization v.1.2.0
Whereas Laravel 5.4 works with work with  Laravellocalization v.1.2.1+

It took me alot of time to find this out, so I thought it would be good to share.
