### ISSUE TITLE
Create configuration file

### ISSUE THREAD

**Issue by azuron** [mcamara/laravel-localization#178]
Hello Marc. I am having a problem when creating a configuration file laravel-localization. I laravel 4.2, in the composer file.json I wrote "mcamara/laravel-localization": "0.15.*"
As well as in the file app/config/app.php I wrote:
'Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider'
'LaravelLocalization' => 'Mcamara\LaravelLocalization\Facades\LaravelLocalization'
Next I ran composer update and installed the package. Your package works with 2 languages perfectly, but I want to add some more languages on my site.
Under Config Files so you can run the command: php artisan vendor:publish to create the configuration file. But I get the error: 
[InvalidArgumentException] 
There are no commands defined in the "vendor" namespace.
Please tell me how to create a configuration file in your package?

**Comment by Thomas-Jensen** [comment]
Hi Azuron, 
So just to be sure you are using the latest release? 

The Laravel-Localization package always created it's own config file, in laravel 5 it's under "vendor/mcamara/laravel-localization/src/config/config.php" I don't recall the complete path in 4.2 but it was the exact same as in the new within the package. 

Kind regards,
Thomas

**Comment by azuron** [comment]
I have the latest version of laravel and Laravel Localization. I already tried to make settings in this file vendor/mcamara/laravel-localization/src/config/config.php. But if I update the package all my settings are removed. I want to create a configuration file in the app directory as written on the website in the section of Config Files.

**Comment by Thomas-Jensen** [comment]
Aah I see, I understand now, actually I had the same problem before (cause I didn't read that section /slaps head) but the command works for me:

![screen shot 2015-02-17 at 13 39 43](https://cloud.githubusercontent.com/assets/9438490/6228321/a3274a44-b6aa-11e4-82fc-c5ee56700eb4.png)

Maybe you have another package which is creating this error?

**Comment by azuron** [comment]
I have this error:
![2015-02-17 16 12 57](https://cloud.githubusercontent.com/assets/8638236/6228672/fabcd69c-b6bf-11e4-9674-55674975ea0d.png)

**Comment by Thomas-Jensen** [comment]
Oh but you have laravel 4.2 not the latest 5.0 and also the 'old' version of the package but that fits teh laravel install, so the problem is that vendor is a 5.0 thing afaik so you gotta look in the old files like this old readme: https://github.com/mcamara/laravel-localization/blob/855fbeae5d9d3d7ef421dd4d247a358cd2551d15/README.md#config

this was the old config option: 

Config

By default only english and spanish are allowed but it can be changed using config.php file that is located at app/config/packages/mcamara/laravel-localization/config.php . If this file does not exist, use the following artisan command php artisan config:publish mcamara/laravel-localization in order to create it.

**Comment by azuron** [comment]
Thank you very much for your help and good advice!!! The command php artisan config:publish mcamara/laravel-localization has created the configuration file here app/config/packages/mcamara/laravel-localization/config.php Thank you it works great!

**Comment by Thomas-Jensen** [comment]
Happy to help :)
