### ISSUE TITLE
routes.translation event listen doesn't work

### ISSUE THREAD

**Issue by fede91it** [mcamara/laravel-localization#322]
I have a language switch bar that has to generate the URL for the current page in all supported languages.

To do that I have to subscribe to the **routes.translation** event, but isn't so simple.

When I execute this

``` php
LaravelLocalization::getLocalizedURL($localeCode); // Where $localeCode is "en", "fr", etc.
```

with this

``` php
Event::listen('routes.translation', function ($locale, $attributes)
{
    foreach ($attributes as $name => $value)
    {
        $attributes[$name] = $translatedValue; // get the transated attribute for the given $locale
    }

    return $attributes;
});
```

I get this error

```
ErrorException in routes.php line 38:
Missing argument 2 for App\Providers\RouteServiceProvider::{closure}() (View: D:\Progetti\instalmec.it\Instalmec\resources\views\header.blade.php) (View: D:\Progetti\instalmec.it\Instalmec\resources\views\header.blade.php)
```

Why? I followed your docs but doesn't work as expected.
I see that the first parameter is the attributes array, but should be the second, right?

See [entire logs](https://github.com/mcamara/laravel-localization/files/313321/logs.pdf) if needed.

**Comment by fede91it** [comment]
+1

**Comment by mcamara** [comment]
To print a language switcher you just need to add this code to your blade template.
```
                @foreach (LaravelLocalization::getSupportedLocales() as $key => $language)
                    <a href="{{ LaravelLocalization::getLocalizedURL($key) }}">
                        {{ $language['name'] }}
                    </a>
                @endforeach
```

Why are you using events for this?

**Comment by fede91it** [comment]
I am using the event because I have to translate the parameters present in the URL, as well as the routes themselves.

We are in **/gasoline/cars** and through the `LaravelLocalization::getLocalizedURL('it')` I want to generate the right translated URL in Italian (which is **/benzina/macchine**). The routes are:

/resources/lang/en/routes.php

```php
return [
    'cars' => '{fuel}/cars'
];
```

/resources/lang/it/routes.php

```php
return [
    'cars' => '{fuel}/macchine'
];
```

The strange behaviors are two.

1. If there is **no listener** for `routes.translation` event, the routes are translated correctly but not the parameters (as expected): `/it/gasoline/macchine`

2. If the **listener exists**, not only the translated parameters returned by it are ignored, nor the routes are translated but the prefix of the language is added: `/it/gasoline/cars` instead of `/it/benzina/macchine` as expected.

Morover, the routes.translation event is fired with only one parameter, the attributes, so I really don't understand how the listener should know which locale use to translate the attributes (now I forced to italian)

**Comment by fede91it** [comment]
Any news here? I debugged the code but I some help to fix this issue

**Comment by fede91it** [comment]
+1 please, I need to solve the problem and I can pay for an help!

**Comment by zarapico123** [comment]
@fede91it the problem is in the file

LaravelLocalization.php # L855
https://github.com/mcamara/laravel-localization/blob/3c14c66df8de72b612d9eaffba23438ee52f5e67/src/Mcamara/LaravelLocalization/LaravelLocalization.php#L855

The event is triggered only with an argument when the documentation says they are two $ locale, $ attributes

@mcamara hopefully can fix the bug please!

**Comment by zarapico123** [comment]
@fede91it @mcamara pull request https://github.com/mcamara/laravel-localization/pull/362

**Comment by marcbelletre** [comment]
I have the exact same problem as @fede91it.
I'm trying to use the event listener in order to translate slugs when using getLocalizedUrl. For example I would like to have the following routes:
- /fr/programmation/spectacles
- /en/program/shows

In my routes translation file I have the following line:
```php
return [
   'program' => 'programmation/{category?}',
];
```

I'm displaying the language switcher using this:
```html
@foreach( LaravelLocalization::getSupportedLocales() as $localeCode => $properties )
   <li>
      <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode) }}"{!! LaravelLocalization::getCurrentLocale() === $localeCode ? 'class="active"' : '' !!}>{{ $localeCode }}</a>
   </li>
@endforeach
```

And finally my event listener in EventServiceProvider.php
```php
Event::listen('routes.translation', function($locale, $attributes) {
   if( array_key_exists('category', $attributes) ) {
      $category = Category::whereTranslation('slug', $attributes['category'])->first();

      if( $category && $category->hasTranslation($locale) ) {
         $attributes['category'] = $category->translate($locale)->slug;
      }
   }
   return $attributes;
});
```

I know the event is firing because I can dump my Category model. However it doesn't change anything in the localized URL.
I get the same behaviors described by @fede91it [here](https://github.com/mcamara/laravel-localization/issues/322#issuecomment-226989764). Without the event listener I get:
- /fr/programmation/spectacles
- /en/program/spectacles

But I get these results with the event listener whatever I write in it:
- /fr/programmation/spectacles
- /en/programmation/spectacles

I know this issue has been closed but it looks like it still hasn't been solved. Or maybe I'm doing something wrong?
I'm using the lastest version (1.3.4) with Laravel 5.5.34.

**Comment by lukkoro** [comment]
> I guess my only solution here is to overwrite this function so it can look for the attributes translations.

Did you manage to solve this issue? I have the same problem where I'm trying to pull localized slug from the database and I know the event is firing but still doesn't translate..
