### ISSUE TITLE
methodnotallowed exception while posting a form.

### ISSUE THREAD

**Issue by yigitozmen** [mcamara/laravel-localization#340]
when i place the post routes inside localized route group, i get methodnotallowed exception.
`Route::group([
    'prefix' => LaravelLocalization::setLocale(),
    'middleware' => [ 'localeSessionRedirect', 'localizationRedirect' ]

], function() {
    Route::post('/offerselect', 'SearchController@getCarList');`

this route, /offerselect won't work when i'm posting. it will return methodnotallowed exception to me.

i'm using laravel 5.1 with latest 1.0.\* version of laravel-localization

**Comment by alex0082ass** [comment]
I have the same issue [https://github.com/mcamara/laravel-localization/issues/344](url)
When the url has locale segment, the post routes do not work..

**Comment by LuciusCaesar** [comment]
Same for me... 
It seems like using 'action()' method when opening the form makes it work while the "url()" method makes it bug...

### Workaround: 

```
{!! Form::open([
    'method' => 'POST', 
    'url' => action('SomeController@store'), 
    'class' => 'form-horizontal'
]) !!}
```
instead of 
```
{!! Form::open([
    'method' => 'POST', 
    'url' => url('/some-url'), 
    'class' => 'form-horizontal'
]) !!}
```
or equivalent if you're not using LaravelCollective/html package...

Though I have no idea about the root cause
I hope it will work for you too.
