### ISSUE TITLE
Keeping the language code in the URL whilst navigating the site

### ISSUE THREAD

**Issue by aidanayala** [mcamara/laravel-localization#359]
I am sure I read through the docs properly, but didn't see anything on this.

Lets say the user is browsing the /contact route. They change to French. So now their route / url is www.example.com/fr/contact.

If they then click another link, say /about. Then they are redirected back to English. www.example.com/about.

Is there anyway we can maintain the URL structure whilst browsing the site?

I am currently using `<a href="{{url('/about')}}">About</a>` to create my in page links. Does this package provide another function which I am missing and would make this easier?

**Comment by vvatitv** [comment]
Check in .env "SESSION_DOMAIN"

> I had the same problem, for example, when i have url: "/en/login" and click on link "home", i have just "/home" without "/en". I'm use hidden default language.

Sorry for my bad english ;)

**Comment by aidanayala** [comment]
Thank you.

So you just replace your in page links with `<a href="{{url(SESSION_DOMAIN . '/about')}}">About</a>`

For example?

**Comment by afontcu** [comment]
I think you should replace `url()` with `route()`, worked for me:

`url('foo')` redirects to domain.com/foo
`route('foo')` redirects to domain.com/es/foo (being "es" my current language).

It might depend on your route.php implementation, but give it a try.

Hope it helps.

**Comment by vvatitv** [comment]
No, no no... 

I don't change routes... 

In .env file, you must check params "SESSION_DOMAIN", that she "identical" your domain...

Example:
My local domain name is: demo.com

my .env:
> SESSION_DOMAIN=demo.com

In rotes i'm nothing write..

I had the same problem on last week, when I tested multilanguage on laravel 5.3, and forgot change this params in .env file, and later two hours i'm just reinstall all progect. Because I thought that it packages conflict...  xD

**Comment by aidanayala** [comment]
Ah, brilliant thank you!
