### ISSUE TITLE
v1.2.* : getLocalizedURL() does not return targeted locale URL

### ISSUE THREAD

**Issue by Okipa** [mcamara/laravel-localization#410]
Since I updated to the the V1.2.3, my links are not translated anymore on the language selector with the getLocalizedURL() method.
Your example bellow is not valid anymore :
```
<ul class="language_bar_chooser">
    @foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
        <li>
            <a rel="alternate" hreflang="{{$localeCode}}" href="{{LaravelLocalization::getLocalizedURL($localeCode) }}">
                {{ $properties['native'] }}
            </a>
        </li>
    @endforeach
</ul>
```

I precise that I loaded back the v1.1.6 to check if that was due to the update and it worked well on this version.
Is it a mistake or is maybe there a new way to get the translated url in a targeted locale ?

**Comment by Okipa** [comment]
This issue is referenced in a pull request : https://github.com/mcamara/laravel-localization/pull/407

**Comment by bouldrini** [comment]
Hey folks, I ran into the same Issue, and solved the problem.

To fix this you got to do changes in your LaravelLocalization.php file.

Problem is, that for calls to $this->translator->trans() functions are given 3 instead of 4 parameters in some cases.
You got to pass 'null' or anything else to these functioncalls als third parameter.

for example:
$this->translator->trans($transKeyName, [], null, $locale)

instead of
$this->translator->trans($transKeyName, [], $locale) 

This worked for me so far.

**Comment by szabizs** [comment]
@bouldrini excellent, that did the trick, thank you!

**Comment by Okipa** [comment]
You're right, but the PR to fix this is still waiting for approval.
Waiting for this fix !
