### ISSUE TITLE
URL scheme Issue https to http

### ISSUE THREAD

**Issue by dhiman252** [mcamara/laravel-localization#477]
my website is https enabled so when the user hit the url it is redirected to the http insted of the https as default scheme

this happens with the `LaravelLocalizationRedirectFilter` when it checks the user browser language and provides a 302 redirect response of http insted of the https

**Comment by lucasff** [comment]
You're doing it wrong. Your web server should be responsible for redirecting `HTTP -> HTTPS` traffic. It is too much time until it hits the PHP application and thus the `RedirectFilter`. When you do it right, any response sent from the Filter will be HTTPS.

**Comment by bionicmaster** [comment]
It's happening to me as well (I just enter to issues to report this), and this happens in this way:
- Some user enters https://your-site.com
- Localization redirects user to http://your-site.com/en with redirect 302 (for example)
- Localization redirects user again from http://your-site.com/en to https://your-site.com/en with a redirect 301

**Comment by lucasff** [comment]
I'm mentioning again, redirection from HTTP to HTTPS should be done Apache or nginx level, not at application! It is faster for the end user!

**Comment by dhiman252** [comment]
I did some research on this issue and found that the problem is not with this package insted please do the following:
in file `app/Providers/AppServiceProvider.php `
just place the following code:

```
if (App::environment('production')) {
     $this->app['request']->server->set('HTTPS', true);
}
```
Hope that helps!!

**Comment by lucasff** [comment]
@dhiman252 the same thing can be achieved in the webserver configuration.

**Comment by bionicmaster** [comment]
@dhiman252 it helped me, thanks (I don't know why the new instruction that replaces this, didn't work)
@lucasff the trouble was not exactly that, we already had http -> https redirection into the server, the trouble was that when some hit HTTPS://example.com it redirected it to HTTP://example.com/en and later to HTTPS://example.com/en because laravel was forcing the redirection to http automatically and again to HTTPS, but was done by laravel directly, not by us or something that we did
