### ISSUE TITLE
POST request Redirection

### ISSUE THREAD

**Issue by zeyad82** [mcamara/laravel-localization#481]
If it's a post request and without a locale in the URL, it's redirected with a locale in the url, but as it will be converted into a GET request, it causes Method Not Allowed Exception. I think there is no point in redirecting POST request so it is better to check and redirect only if it's a GET Request, isn't it?

**Comment by DCdeBrabander** [comment]
I have this issue as well. Primariliy by using XHTTP requests.
Is there an solution for this?

**Comment by iwasherefirst2** [comment]
> If it's a post request and without a locale in the URL, it's redirected with a locale in the url, but as it will be converted into a GET request, it causes Method Not Allowed Exception. I think there is no point in redirecting POST request so it is better to check and redirect only if it's a GET Request, isn't it?

This only happens if you put a POST url inside your `Routes::group`. You should either put the `post` route outside your group and use [PSR pattern] to redirect to a localized url, or add the locale in your post url otherwise (See https://github.com/mcamara/laravel-localization/issues/634#issuecomment-541147504)
