### ISSUE TITLE
Route with dynamic parameters & language switch

### ISSUE THREAD

**Issue by Grupa-Leonardo** [mcamara/laravel-localization#562]
Hi,
I have routes with dynamic parameters, e.g.
`Route::get(LaravelLocalization::transRoute('page/catalog.routes.page').'/{catalogSlug}', 'Website\CatalogController@index');`
and I have lang switcher:
```
@foreach(LaravelLocalization::getSupportedLocales() as $localeCode => $properties)
    <li>
        <a
            @if($localeCode == Request::segment(1)) class="active" @endif
            rel="alternate"
            hreflang="{{ $localeCode }}"
            href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) }}">
            {{ $localeCode }}
        </a>
    </li>
@endforeach
```
but when I switching language I have correct only lang suffix - why?

**Comment by borealsmith** [comment]
Hi, 

I noticed this issue. 
I assume that instead of getLocalizedUR one should use the getURLFromRouteNameTranslated helper function.
The subsequent issue of doing so is that when using getURLFromRouteNameTranslated along with Route Model Binding the JSON version of the Model will be inserted in the url instead of model id valie.

Cheers,

**Comment by iwasherefirst2** [comment]
The slugs should be in the `routes.php` file: https://github.com/mcamara/laravel-localization/issues/502#issuecomment-546670758
