### ISSUE TITLE
Feature: Subdomains with Middleware

### ISSUE THREAD

**Issue by pmochine** [mcamara/laravel-localization#568]
With the current Middleware, you cannot use subdomains. It would be awesome to use it. I still need to read a bit of code, but would it be hard to do?

**Comment by philmarc** [comment]
You can use `Route::domain`

https://laravel.com/docs/5.8/routing#route-group-sub-domain-routing

**Comment by pmochine** [comment]
@philmarc thanks but that won't really help so I created my own package https://github.com/pmochine/Laravel-Tongue

Thanks nonetheless :)

**Comment by natxet** [comment]
Hi, it's very easy to do @philmarc 
On your `config/laravellocalization.php` use the `localesMapping` array to define your domains like this (I'm even using the ENV to have different domain names for local environment):

    'localesMapping' => [
        env('HOSTNAME_ES', 'domain.es') => 'es',
        env('HOSTNAME_EN', 'domain.com') => 'en',
    ],

Then, when you create your group in the `routes/web.php` use the `domain` instead of the `prefix`to set the domain:

    Route::group([
        'domain' => LaravelLocalization::setLocale(),
        'middleware' => ['localizationRedirect', 'localeViewPath']
    ], function () {

It worked like charm to me! Even using the transRoute() feature :-)

**Comment by pipisco** [comment]
Hello everyone! I create this solution in https://github.com/movemoveapp/laravel-localization#localization-switch-by-domain-names. Loot at this please. 

Thank you.
