### ISSUE TITLE
Middleware to set Default locale

### ISSUE THREAD

**Issue by elnurxf** [mcamara/laravel-localization#621]
Created a Middleware which is based on a ```$request->server('HTTP_CF_IPCOUNTRY')``` and should set default locale based on a visitors country. There is mapping for Country code => Default locale.

Is there any way to set Default locale, because methods are not working as expected, since laravel-localization already loaded default locale from config:

- ```app()->setLocale($country_locale);```
- ```Config::set('app.locale', $country_locale);```
- ```App::setLocale($country_locale);```
- ```\Mcamara\LaravelLocalization\Facades\LaravelLocalization::setLocale($country_locale);```

Thank you in advance.

**Comment by slowas** [comment]
I'am have same problem..

**Comment by hedii** [comment]
Same problem since the laravel 5.8 update.
Same use case: a middleware to set the locale based on a request header, and using trans route caching gives me 404 for all these routes.

Here is the LocalizeRequests middleware:

```php
<?php

namespace Foo;

use Closure;

class LocalizeRequests
{
    /**
     * Handle an incoming request.
     *
     * @param \Illuminate\Http\Request $request
     * @param \Closure $next
     * @return mixed
     */
    public function handle($request, Closure $next)
    {
        app()->setLocale($request->header('X-Locale', config('app.fallback_locale')));

        return $next($request);
    }
}
```

**Comment by iwasherefirst2** [comment]
> Created a Middleware which is based on a $request->server('HTTP_CF_IPCOUNTRY') and should set default locale based on a visitors country.
>
>Is there any way to set Default locale, because methods are not working as expected, since laravel-localization already loaded default locale from config:

You may want to use `useAcceptLanguageHeader` instead which will redirect to the language of the visitors browser language settings. This is usually the best option, because user may have multiple preferred languages with different rankings. Also, there are countries who use multiple languages(how you deduce the language from the country?).

If you insist to redirect the user  based on `$request->server('HTTP_CF_IPCOUNTRY') ` instead of  `useAcceptLanguageHeader`, then just compute the correct language on your own and redirect accordingly. For example if a user first wants to visit `yourdomain.com/gardening` and you compute the language should be `it` based on his language, you need to redirect to `yourdomain.com/it/gardening` in your middlware. 

When doing so, one should make sure that your middleware only works when user visits the page for the first time. Because you probably don't want to redirect `yourdomain.com/de/gardening` to `yourdomain.com/it/gardening`, because then the user can't switch the language.
If you use the option `hideDefaultLocaleInURL`, then you need to use session to find if a user visited a page for the first time. 

I recommend to take a look at `LaravelLocalization/Middleware/LocaleSessionRedirect`.

**Comment by elnurxf** [comment]
I've already solve this. Here is a gist: https://gist.github.com/elnurxf/7e36bb81f8c22e9d2b38e1cf67d7d47f

**Comment by iwasherefirst2** [comment]
I would recommend to redirect, otherwise one will get SEO problems with duplicate content for the same uri. Also note that you code is not compatible with `hideDefaultLocaleInURL`.

**Comment by elnurxf** [comment]
We've canonical URL in <header> to point corresponding version of the web-site.
