### ISSUE TITLE
Remove locale from uri, even if it's not the default one 

### ISSUE THREAD

**Issue by jlefebvre1997** [mcamara/laravel-localization#627]
Hi guys, everything is in the title. 
I want to be able to generate my routes without having the locale in it, but as I checked in the files, I'm wondering if it's really possible... Could you help me on it ? 

Thanks for your time and help !

**Comment by groupegarryhost** [comment]
I have the same problem

**Comment by iwasherefirst2** [comment]
You want the same uri for different content? 

This is a huge problem for the SEO ranking of your page, because search engines won't understand that you have different langauges all on the same uri with mixed content.

If you want it despite bad SEO results, I would not recommend to use this package, because its made for a different purpose.

Just use `App::isLocale` inside your blade files,

```
@if (App::isLocale('en')) 
 ... 
@elseif(App::isLocale('de'))
...
@endif 
```

 or create a middleware to detect which blade file should be loaded.

**Comment by groupegarryhost** [comment]
I'm having issue switching language on my index but don't understand why...

When I access domain.app and switch language it redirect me to domain.app/en
But locale doesn't switch. I have to access link domain.com/en/ (slash at the end) and then it's working fine. But why?
I can solve this by having index URL: domain.com/home but I don't want to have any slug on index.

**Comment by iwasherefirst2** [comment]
> I'm having issue switching language on my index but don't understand why...

Maybe you should open another issue then. This question here is a feature request and not a bug report. Namly removing the locale from the uri (and I described above why this is bad for SEO and how to achieve it simply without this package)?

> When I access domain.app and switch language it redirect me to domain.app/en
> But locale doesn't switch. I have to access link domain.com/en/ (slash at the end) and then it's working fine. But why?

This is strange, because by default a uri with traling slash is redirected to the uri without trailing slash (expect you have an folder "en" in your public folder).

```
  # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]
```

> I can solve this by having index URL: domain.com/home but I don't want to have any slug on index.

If you really have this issue, please create new Laravel package and tell us step by step what you did, what you expect and what happened.
