### ISSUE TITLE
array_flip() expects parameter 1 to be array, null given

### ISSUE THREAD

**Issue by Sohail-Ansari** [mcamara/laravel-localization#640]
In LaravelLocalization.php line 446:

  array_flip() expects parameter 1 to be array, null given

Script @php artisan package:discover handling the post-autoload-dump event returned with error code 1

**Comment by CastenWaryn** [comment]
I'm getting this same error on a fresh install of Lavalite 5.8

**Comment by lucas-quinn-guru** [comment]
> I'm getting this same error on a fresh install of Lavalite 5.8

same here.

**Comment by lucas-quinn-guru** [comment]
I was able to get passed this.  Unfortunately, it a cart before the horse scenario.  It looks for the config file of laravellocalization, but it doesn't exist on a clean install.

I create a config fill for laravellocalization.  Do the following.

Create laravellocalization.php in app/config.

Copy the contents of https://raw.githubusercontent.com/mcamara/laravel-localization/master/src/config/config.php to this file.

That's all there is to it.  

This file would be automatically created through `php artisan vendor:publish --provider="Mcamara\LaravelLocalization\LaravelLocalizationServiceProvider"` but we never could get this far because of the error.  Hence, cart before the horse.

**Comment by omacesc** [comment]
Any news about this issue, I've the same problem.

**Comment by charliex2** [comment]
I'm getting this same error on a fresh install of Lavalite 5.8

**Comment by iwasherefirst2** [comment]
I just installed a fresh Laravel 5.8 version and installed this package:

    composer require mcamara/laravel-localization

it worked out of the box. Can you still reproduce the issue? If so, which PHP version are you using?

**Comment by iwasherefirst2** [comment]
I have installed Lavalite 5.7 and did not get this error. Where did you get 5.8 from? Its not on packagist: https://packagist.org/packages/lavalite/cms

**Comment by Lerz** [comment]
I just get this error when trying to update from Laravel 5.4.
I tried to remove the packet, update it from 1.3 to 1.x
Nothing work, I got this error.

I have a configured laravellocalization.php in app/config.
