### ISSUE TITLE
Error 404 when use cached routes in Laravel 6

### ISSUE THREAD

**Issue by lsfiege** [mcamara/laravel-localization#650]
Hello! When caching routes the default language not works ant it throw an 404 error. This staring to happen in Laravel 6.

Also I'm using the hideDefaultLocaleInURL option with true value. **Edited

**Comment by cocochepeau** [comment]
Hi,

I'm having 404 issues as well, but without setting hideDefaultLocaleInURL to true. Routes are cached.

It happens on URLs like `localhost/myroute`. The automatic redirection to `localhost/lang/myroute` doesn't work and respond with 404.

**Comment by cocochepeau** [comment]
(I'm using 5.8 btw!)

**Comment by ben182** [comment]
Same here on 5.8 with default settings (hideDefaultLocaleInURL false)

**Comment by dizco** [comment]
This happens with release 1.4.1. I have tested with 1.4.0 and everything was fine.

Basically here are my repro steps:
1. Have a root url (in my case, I have `hideDefaultLocaleInURL` to false, and `useAcceptLanguageHeader` to true.
2. Set a `routes.php` translation file
    ```php
    return [
        'index' => '/',
    ];
    ```
    
3. Define routes
    ```php
    Route::group(
        [
            'prefix' => LaravelLocalization::setLocale(),
            'middleware' => ['localize', 'localeCookieRedirect', 'localeSessionRedirect', 'localizationRedirect']
        ],
        function() {
            Route::get(LaravelLocalization::transRoute('routes.index'), 'WebController@getIndex');
        }
    );
    ```

4. Run `php artisan route:trans:cache`

5. Try to hit the root endpoint and get a 404. All other routes work. The root also works after you `php artisan route:trans:clear`.

This issue seems to have been introduced by #646, but I can't determine the exact problem with it.

**Comment by mitjazeleznikar** [comment]
Any update on this one? I also rolled back to 1.3.20 and works fine.

**Comment by mcamara** [comment]
New version of the package should fix this issue, thanks for your help

**Comment by tariksisbacak** [comment]
Hi, I have the same problem.

I have updated to version 1.4.2 but it does not work.
"localeSessionRedirect" Middleware does not include the default url in the route

http://egeoptik.test/            (English default)
http://egeoptik.test/de

Redirects to site.test / de instead of site.test / if session is defined

I have read a lot of issues but nothing changed
