### ISSUE TITLE
'localeSessionRedirect' does not work. #664

### ISSUE THREAD

**Issue by tariksisbacak** [mcamara/laravel-localization#672]
The problem still continues. locale does not work default language when I add 'localeSessionRedirect' 

I tried route:trans:cache, the result is still the same

```
Route::group(['namespace' => 'Frontend', 'prefix' => LaravelLocalization::setLocale(), 'middleware' => ['web', 'localize', 'localizationRedirect', 'localeViewPath']], function () {

    Route::get(LaravelLocalization::transRoute('routes.home'), [
        'as' => 'frontend.home',
        'uses' => 'Home\HomeController@index'
    ]);
]);
```
```
'useAcceptLanguageHeader' => false,

 'hideDefaultLocaleInURL' => true,

```

@iwasherefirst2 

#664

**Comment by iwasherefirst2** [comment]
You did not mention that you use `transRoute` in #661. But anyway it should work.

I have a fresh installation of Laravel. Here is an example:

`routes/web.php`:

```
Route::group(['prefix' => LaravelLocalization::setLocale(), 'middleware' => [ 'localize', 'localeSessionRedirect', 'localizationRedirect']], function () {
    Route::get(LaravelLocalization::transRoute('routes.about'), function () {
        return \App::getLocale();
    });
});
```

`resources/lang/es/routes.php`: 
```

<?php

return [
	"about" 	=> 	"acerca",
	"view" 		=> 	"ver/{id}", //we add a route parameter
	// other translated routes
];
```

`resources/lang/en/routes.php`: 

```
<?php

return [
    'about' 	=> 	'about',
    'view' 		=> 	'ver/{id}', //we add a route parameter
    // other translated routes
];
```
I am using locales `en` and `es` and `useAcceptLanguageHeader` is false, `hideDefaultLocaleInURL` is true,

The following urls work:
```

example.test/about (redirects to es if stored in session)
example.test/en/about ->  example.test/about 
example.test/es/acerca 
```

So everything seems to work. What exactly is not working for you? 

Please try to stick to the issue template (Expected behaviour, how to reproduce etc.)

**Comment by tariksisbacak** [comment]
n fact everything is right. I added 'locale Session Redirect' and it worked.
I was surprised. Normally I couldn't start it.

Thank you @iwasherefirst2  :-)
