### ISSUE TITLE
Can I use AcceptLanguageHeader + hideDefaultLocaleInURL in 1.0.13?

### ISSUE THREAD

**Issue by neosaganeo** [mcamara/laravel-localization#719]
Hello. I like your project very much and hope to use it. But since my project is based on laravel 5.1 + PHP 7.0, I can only use version 1.0.13 of your project. Therefore, I have the same problem as the following:

https://github.com/mcamara/laravel-localization/issues/305

I don't know if you can release a new version of 1.0.13 that fixes this problem? I guess there are still a lot of projects that need to be maintained that are developed using laravel 5.1. Thank you very much and looking forward.

**Comment by iwasherefirst2** [comment]
I would highly recommend to upgrade your Laravel version. Security fixes have been stopped since June 2018: https://laravel.com/docs/5.8/releases

The feature has been build in since release [1.3.16](https://github.com/mcamara/laravel-localization/releases/tag/1.3.16)  which is available for Laravel version starting at 5.2

If you do not want to upgrade, then I guess the only way to go is to fork 1.0.13 and try to apply the changes from https://github.com/mcamara/laravel-localization/pull/599/files, but I can't guaratee if it works, there were a ton of upgrades between 1.0.13 and 1.3.16
