### ISSUE TITLE
E-mails don't translate routes

### ISSUE THREAD

**Issue by reinierkors** [mcamara/laravel-localization#733]
When using laravel-localization with e-mail templates like:
```php
{{ URL::signedRoute('unsubscribe', ['email' => $user->email]) }}
```

The URL generated won't use the translated route. For signed routes this means the signed validation will also fail because users get redirected to the translated URI because of the redirect middleware.

I use the preferred locale in the User-model:
```php
public function preferredLocale()
{
    return $this->language;
}
```

Meaning the strings do get translated, but when using any function like:
```php
{{ LaravelLocalization::localizeUrl('/test') }}
```

It will still default to the original language.

I've tried using:
```php
LaravelLocalization::setLocale($this->user->language);
```
but without luck.

**Comment by thomlemee** [comment]
To get your signed URL localized you can directly pass the URL to the localizeURL helper.

```php
LaravelLocalization::localizeUrl(
  URL::signedRoute('unsubscribe', ['email' => $this->user->email]),
  $this->user->language
);
```
And passing the user language as the second parameter, to ensure that the correct locale is used.

**Comment by jeff-h** [comment]
@thomlemee I'm confused — the code snippet above will add the locale code prefix to the signed route, right? After which the resulting URL will surely not pass signature validation?

```
# This URL will validate ie hasValidSignature() is true
https://site.com/routename?expires=1629877846&signature=337a56b7a5e...e812ecefbc680f4f

# This URL will not validate:
https://site.com/de/routename?expires=1629877846&signature=337a56b7a5e...e812ecefbc680f4f
```

**Comment by thomlemee** [comment]
You are right. I answered way to fast. I see multiple alternatives :
- Sign a non localised route, perform all the logic and then redirect to a localised confirmation page
- Explore [codezero-be/laravel-localized-routes](https://github.com/codezero-be/laravel-localized-routes#-generate-signed-route-urls) which does have an option for this case
- Find a package that can sign URL and is not restricted to named routes

**Comment by jeff-h** [comment]
Thanks for clarifying :)

Hmm, the codezero package is looking very nice indeed. Thanks for bringing it to my attention!

**Comment by jeff-h** [comment]
Despite my enthusiasm above we ended up staying with this package for various reasons, a decision that's largely played out really well for us (thanks @mcamara for all your work!)

I again had to revisit this issue and thought I'd post my solution in case it helps others.

**The problem**
Laravel can only generate signed URLs from *named routes* which involves the routes definitions and thus middleware; when a signed URL is generated inside a queue worker (as when sending emails) there's no locale set and the resulting named route's URL has no locale prefix (`/de/`, `/en/` etc).

When the user clicks one of these links in an email, laravel-localisation middleware sends them to a URL with a locale prefix, which will not pass the URL's signature validation, since the URL is different (it has a `/de/` in it, or whatever).

**What I tried**
I really wanted to get the links correct in the emails. To achieve this I tried to get a Laravel queue worker to generate a signed route *with my choice of locale prefix*. Using the existing Laravel API I don't think it's possible. I tried every which way, short of writing a clone of Laravel's signing code. 

**My solution / workaround**
The signed links in the emails do not contain a locale prefix. The Laravel code that checks the link signatures is operating in an environment that *does* have local prefixes and thus the email links fail validation.

My solution is to remove the locale from the current URL, create a `Request` from that URL, and run the validation check on that. Pretty simple, I guess.

```php
$localeRemovedUrl = LaravelLocalization::getNonLocalizedURL();
$localeRemovedRequest = Request::create($localeRemovedUrl);

$valid = $localeRemovedRequest->hasValidSignature();
```

In my case I wrapped it in a macro on `Request` so I can call it anywhere like so: `$request->nonLocaleHasValidSignature()`.
