### ISSUE TITLE
Redirect en to en-US

### ISSUE THREAD

**Issue by rolandstarke** [mcamara/laravel-localization#805]
Given you have `en-US` configured as available language.

Sometimes users manually change the language in the url and type in `en`. Right now this results in a 404.

I would like that `en` redirects to `en-US`.

Like its done in the Mozilla docs:
https://developer.mozilla.org/en/docs/Web/HTML/Element/input redirects to
https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input
or the other way around
https://developer.mozilla.org/de-CH/docs/Web/HTML/Element/input and
https://developer.mozilla.org/de-AT/docs/Web/HTML/Element/input redirects to
https://developer.mozilla.org/de/docs/Web/HTML/Element/input

I am not sure how to implement it, maybe a new configuration. Or use the `en` as if it has come from the Accept-Language header.

**Comment by iwasherefirst2** [comment]
Well you have to implement something like this by yourself, the package does not offer such a thing. If you want to do it from application side, then I would recommend to create a middleware. Take a look at the middleware of our package for inspiration how to get the locale from the url. Otherwise, you can also adda  redirect rule in your htaccess file.
