### ISSUE TITLE
Redirect to main lang now work with hideDefaultLocaleInURL = true

### ISSUE THREAD

**Issue by igramnet** [mcamara/laravel-localization#842]
I have a code in a blade

```
@php
    $j = 0;
    @endphp
    @foreach(LaravelLocalization::getLocalesOrder() as $localeCode => $properties)
        @php
            $j ++;
        @endphp
        @if($j === 1)
            <a hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], false) . '/' }}">
                {{ $properties['native'] }}
            </a>&nbsp;
        @else
            <a rel="alternate" hreflang="{{ $localeCode }}" href="{{ LaravelLocalization::getLocalizedURL($localeCode, null, [], true) . '/' }}">
                {{ $properties['native'] }}
            </a>&nbsp;
        @endif
    @endforeach
```

And code in routes/web.php

```
/** ADD ALL LOCALIZED ROUTES INSIDE THIS GROUP **/
Route::group(
    [
        'prefix' => LaravelLocalization::setLocale(),
        'middleware' => ['localeSessionRedirect', 'localizationRedirect', 'localeViewPath']
    ], function () {

    Route::get('/', function () {
        return view('index');
    });

    /* Blog */
    Route::get('/blog/', [BlogController::class, 'index'])->name('blog.index');
    /* END Blog */
});
/** OTHER PAGES THAT SHOULD NOT BE LOCALIZED **/
```

1. I open the page http://127.0.0.1/blog
2. Click to another lang (for example EN) and go to http://127.0.0.1/en/blog
3. I click to the first lang (without prefix) and the page redirected to http://127.0.0.1/en/blog, but should to http://127.0.0.1/blog with default lang.

**Comment by iwasherefirst2** [comment]
This is the expected behavior when the [localeSessionRedirect](https://github.com/mcamara/laravel-localization?tab=readme-ov-file#localesessionredirect) middleware is enabled.

Here’s how it works:

-When you visit `http://127.0.0.1/en/blog`, the `en` locale is stored in the session.
-If you then navigate to `http://127.0.0.1/blog`, it redirects you to the lang stored in the session (`en` in this case).
-If there’s no lang in the session, it defaults to the language that matches your browser’s priorities.

To return to the default language (e.g., `de`), you need to explicitly visit `http://127.0.0.1/de/blog`.

If you don’t like this behavior, you can simply remove the `localeSessionRedirect` middleware from your route group. This will disable session-based redirection, and the application will no longer remember the last selected locale.

Let me know if you have further questions or need additional clarification!
