### ISSUE TITLE
When I 

### ISSUE THREAD

**Issue by hamedgasemi200** [mcamara/laravel-localization#854]
When I use `Mcamara\LaravelLocalization\Middleware\LocaleCookieRedirect`, and try to return a file with `response()->file()` in my Laravel project it returns:

```
Call to undefined method Symfony\Component\HttpFoundation\BinaryFileResponse::withCookie()
```

I'm using Passport, too; it seems there are some conflicts between these 2 packages

https://stackoverflow.com/questions/43593351/call-to-undefined-method-symfony-component-httpfoundation-responseheader

>  just found the solution to this issue. The reason why we get this error is because Response object we get in middleware is usually an instance of `Illuminate\Http\Response` class which we can set Response headers using the method `header('Header-Key', 'Header-Value')` **whereas the Request handled by Passport will be an instance of Symfony\Component\HttpFoundation\Response that's why we got the error**``

use `header()` instead of `$response->withHeader();` and similar methods.

Please fix it. Thanks.

**Comment by iwasherefirst2** [comment]
The problem happens because of the middleware of passport package, as it does not return the normal `Illuminate\Http\Response` object. The issue was on Laravel 5, on Laravel Passport <= v4.0.2.

Please update Laravel Passport to anything higher then v4.0.2 (current version is 11.8) and it should be fixed.

Otherwise, you can simply create your own middleware, if an upgrade is not feasible.
