### ISSUE TITLE
In laravel 10 there is no $routeMiddleware

### ISSUE THREAD

**Issue by engmonged** [mcamara/laravel-localization#867]
In laravel 10 there is no $routeMiddleware where can i put  this 
   /**** OTHER MIDDLEWARE ****/
        'localize'                => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
        'localizationRedirect'    => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
        'localeSessionRedirect'   => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
        'localeCookieRedirect'    => \Mcamara\LaravelLocalization\Middleware\LocaleCookieRedirect::class,
        'localeViewPath'          => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class

**Comment by alihan0** [comment]
> In laravel 10 there is no $routeMiddleware where can i put this /**** OTHER MIDDLEWARE ****/ 'localize' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class, 'localizationRedirect' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class, 'localeSessionRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class, 'localeCookieRedirect' => \Mcamara\LaravelLocalization\Middleware\LocaleCookieRedirect::class, 'localeViewPath' => \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class

There is no  `protected $routeMiddleware [...]` for Laravel 10.x.

To run, you can add it to protected `$middlewareGroups[...]` or protected `$middlewareAliases[...]` in `app/http/kernel.php`. either way will work, just if you prefer to add in group you have to change our usage as follows.

`app/http/kernel.php`
```
protected $middlewareGroups = [
       ....
      'localize' =>[
                    \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRoutes::class,
                    \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter::class,
                    \Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect::class,
                    \Mcamara\LaravelLocalization\Middleware\LocaleCookieRedirect::class,
                    \Mcamara\LaravelLocalization\Middleware\LaravelLocalizationViewPath::class
             ] 
];
```
`routes/web.php`

```
Route::group(
[
	'prefix' => LaravelLocalization::setLocale(),
	'middleware' => [ 'localize' ]
], function(){ //...
});
```



On the other hand, despite the installation, localization within the blade templates worked fine but not within the controller. I've been searching for a solution to this for a few days and realized that the problem was url redirection. Although the sessions change, the `setLocale()` method does not work as it should. I found a workaround for this,

`axios.post( '{{ \LaravelLocalization::localizeURL("/auth/login/control") }}', {...}` this way, manually changing the request urls I make to my controllers works.



Sorry for bad English ^^ Goog Code!
